application:
  date-time-format: dd.MM.yyyy HH:mm:ss     # russian also dd.mm.yyyy
  date-time-format-js-moment: DD.MM.YYYY HH:mm:ss
  locale: hr_HR

server:
  port: 8085

spring:
  mvc:
    locale: ${application.locale}

